# Generated by Django 5.2.8 on 2025-12-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100, unique=True)),
                ('spoc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spoc_email', models.CharField(blank=True, max_length=100, null=True)),
                ('spoc_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('client_urls', models.URLField(blank=True, max_length=255, null=True)),
                ('client_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('created_browser', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to='accounts.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_updated', to='accounts.user')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
