# Generated by Django 5.2.8 on 2025-12-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0002_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='e702c956-1242-4f8a-95bc-e732a3282907', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
