# Generated by Django 5.2.8 on 2025-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0003_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='442a2b7a-a78f-440b-a5d6-9b90faece150', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
