# Generated by Django 5.2.8 on 2025-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0004_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='20cf32a1-8e48-4c2a-9dd2-790e9108284d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
