# Generated by Django 5.2.8 on 2025-12-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0005_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='8c118158-70c4-407d-b3ac-af9451a7d0c5', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
