# Generated by Django 5.2.8 on 2025-12-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0006_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='7ca60e35-ffc7-4f01-bdac-cfd0ef33559b', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
