# Generated by Django 5.2.8 on 2025-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0007_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='834ac571-1835-4f68-bbe8-726cb87a18c0', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
