# Generated by Django 5.2.8 on 2025-12-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0008_alter_client_options_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='db176521-505d-467f-b50d-2addff395dcc', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
