# Generated by Django 5.2.8 on 2025-12-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0010_alter_client_client_id_clientconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='0ed8f51c-bc88-4136-a865-4a976442142f', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='clientconfig',
            table='client_config',
        ),
    ]
