# Generated by Django 5.2.8 on 2025-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0011_clientconfig_is_active_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='5c18200f-aaa4-40ee-bb34-cda3560796a5', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
