# Generated by Django 5.2.8 on 2025-12-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0012_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='d15292d1-8ee3-44a3-9f68-c081b5709ebf', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
