# Generated by Django 5.2.8 on 2025-12-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_owner', '0013_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='6a683fed-5d82-47f3-ac87-a3d39e8edb6d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
