# Generated by Django 5.2.8 on 2025-12-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_operator_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='a60d30b5-79ce-45c2-ba01-3fb10422217c', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
