# Generated by Django 5.2.8 on 2025-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='e4d6e6ff-fe47-4f68-b9dd-7de7019c4f34', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
