# Generated by Django 5.2.8 on 2025-12-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='f97d7dce-1298-41a9-8b74-61fcd335f07a', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
