# Generated by Django 5.2.8 on 2025-12-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='aa78323f-0a66-4057-b7da-77707506ee16', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
