# Generated by Django 5.2.8 on 2025-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_options_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='319764de-dfa2-441a-a5a7-d27e4fad24fa', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
