# Generated by Django 5.2.8 on 2025-12-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='c5fb279d-91ca-467c-9df9-e2020f6763f2', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
