# Generated by Django 5.2.8 on 2025-12-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='cc7c07ae-d62f-449f-948d-84e7c73b0a90', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
