# Generated by Django 5.2.8 on 2025-12-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='c46dfb35-72d9-49ca-847c-8339c7b4e83c', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
