# Generated by Django 5.2.8 on 2025-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='d107fa38-ac15-40e3-8846-4ba30510c95b', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='passwordreset',
            table='password_reset',
        ),
    ]
