# Generated by Django 5.2.8 on 2025-12-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_user_id_alter_passwordreset_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='d5623c87-a851-4424-8557-ec93516cfad7', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
