# Generated by Django 5.2.8 on 2025-12-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='55847ad4-45f5-45b5-80a1-8d73c8acfba6', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
