# Generated by Django 5.2.8 on 2025-12-01 05:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('product_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('created_browser', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_owner.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments_created', to='accounts.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_updated', to='accounts.user')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=255)),
                ('process_desc', models.CharField(max_length=255)),
                ('est_process_time', models.IntegerField()),
                ('no_of_steps', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_owner.client')),
            ],
            options={
                'db_table': 'processes',
            },
        ),
        migrations.CreateModel(
            name='OperatorSession',
            fields=[
                ('operator_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.IntegerField(unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('incomplete', 'Incomplete'), ('restart', 'Restart')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_sessions', to='product_owner.client')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_sessions', to='accounts.user')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_sessions', to='client.process')),
            ],
            options={
                'db_table': 'operator_sessions',
            },
        ),
        migrations.CreateModel(
            name='OperatorProcess',
            fields=[
                ('operator_process_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_processes', to='product_owner.client')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_processes', to='accounts.user')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_processes', to='client.process')),
            ],
            options={
                'db_table': 'oprator_process',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=255)),
                ('step_desc', models.CharField(max_length=255)),
                ('est_step_time', models.IntegerField()),
                ('step_sr_no', models.IntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.process')),
            ],
            options={
                'db_table': 'steps',
            },
        ),
        migrations.CreateModel(
            name='SessionStep',
            fields=[
                ('session_step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_session_id', models.IntegerField(unique=True)),
                ('step_sr_no', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_sec', models.IntegerField(blank=True, null=True)),
                ('content_used', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='FALSE', max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_steps', to='product_owner.client')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_steps', to='client.operatorsession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_session_steps', to='client.step')),
            ],
            options={
                'db_table': 'session_steps',
            },
        ),
        migrations.CreateModel(
            name='StepContent',
            fields=[
                ('step_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('text', 'Text')], max_length=20)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.step')),
            ],
            options={
                'db_table': 'step_contents',
            },
        ),
        migrations.CreateModel(
            name='StepContentDetail',
            fields=[
                ('step_content_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_id', models.IntegerField(unique=True)),
                ('file_url', models.CharField(max_length=255)),
                ('duration_or_no_pages', models.IntegerField(blank=True, null=True)),
                ('step_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='client.stepcontent')),
            ],
            options={
                'db_table': 'step_content_details',
            },
        ),
        migrations.CreateModel(
            name='SessionStepContentUsage',
            fields=[
                ('session_step_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('usage_id', models.IntegerField(unique=True)),
                ('step_content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('text', 'Text')], max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_owner.client')),
                ('step_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_usages', to='client.sessionstep')),
                ('step_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='client.stepcontent')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.stepcontentdetail')),
            ],
            options={
                'db_table': 'session_step_content_usage',
            },
        ),
        migrations.CreateModel(
            name='StepContentVoiceOver',
            fields=[
                ('step_content_voice_over_id', models.AutoField(primary_key=True, serialize=False)),
                ('voice_over_file_type', models.CharField(choices=[('audio', 'Audio'), ('tts', 'Text To Speech')], max_length=10)),
                ('file_url', models.CharField(max_length=255)),
                ('step_content_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_overs', to='client.stepcontentdetail')),
            ],
            options={
                'db_table': 'step_content_voice_over',
            },
        ),
        migrations.CreateModel(
            name='StepContentCaptions',
            fields=[
                ('caption_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=255)),
                ('caption_file_type', models.CharField(choices=[('vtt', 'WebVTT'), ('srt', 'SubRip')], max_length=10)),
                ('step_content_voice_over', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='client.stepcontentvoiceover')),
            ],
            options={
                'db_table': 'step_content_captions',
            },
        ),
        migrations.CreateModel(
            name='VRDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('device_make', models.CharField(blank=True, max_length=255, null=True)),
                ('device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('created_browser', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_owner.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vrdevice_created', to='accounts.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vrdevice_updated', to='accounts.user')),
            ],
            options={
                'db_table': 'vr_device',
                'unique_together': {('device_name', 'client')},
            },
        ),
    ]
