# Generated by Django 5.2.8 on 2025-12-05 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_process_is_active_step_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='step_content_voice_over',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='client.stepcontentdetail'),
        ),
    ]
