# Generated by Django 5.2.8 on 2025-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_stepcontentcaptions_step_content_voice_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='language_id',
            field=models.CharField(max_length=10),
        ),
    ]
