# Generated by Django 5.2.8 on 2025-12-05 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_stepcontentdetail_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepcontentvoiceover',
            name='language',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stepcontentvoiceover',
            name='language_id',
            field=models.CharField(default='EN', max_length=10),
            preserve_default=False,
        ),
    ]
