# Generated by Django 5.2.8 on 2025-12-13 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_operatorprocess_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprocess',
            name='operator_process_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session_step_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='step_session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='usage_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontent',
            name='step_content_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='caption_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='step_content_voice_over',
            field=models.ForeignKey(db_column='step_content_detail_id', on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='client.stepcontentdetail'),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='language_id',
            field=models.CharField(db_column='content_language_id', max_length=10),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='step_content_detail_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentvoiceover',
            name='step_content_voice_over_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrdevice',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
