# Generated by Django 5.2.8 on 2025-12-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_operatorprocess_operator_process_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.UUIDField(default='3461a09c-e3ab-42a2-953b-c553d3c63a08', editable=False, primary_key=True, serialize=False),
        ),
    ]
