# Generated by Django 5.2.8 on 2025-12-14 06:07

import apps.client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_process_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.UUIDField(default=apps.client.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
