# Generated by Django 5.2.8 on 2025-12-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_process_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='0092cea6-cf29-489c-b65e-070141e2a540', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
