# Generated by Django 5.2.8 on 2025-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_process_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='342aa81c-49a4-42b2-9bd2-2280e2c8336c', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.CharField(default='d9e35d06-e9a2-4b43-8c35-a7e666ad0c75', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
