# Generated by Django 5.2.8 on 2025-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_operatorprocess_operator_process_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operatorprocess',
            name='operator_process_id',
            field=models.CharField(default='89e3906b-0b1f-4dc7-95fa-dda695561681', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.CharField(default='a1791a51-12e5-447e-9c99-5723e6c0959a', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='session_id',
            field=models.CharField(default='fb95edf8-a635-4f60-a6b4-bf7a9426c2f9', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='95560cec-30cc-451f-93a5-7450f6b38adf', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session_step_id',
            field=models.CharField(default='20dec176-3498-4d61-abee-1fb91b530a4f', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='step_session_id',
            field=models.CharField(default='b1dc0ca6-2876-4681-86fc-b435008a7038', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.CharField(default='b9638981-0929-4fee-945b-80229dfd262c', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='usage_id',
            field=models.CharField(default='08a9c6ca-555b-452f-9987-39ce5f78e887', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.CharField(default='e8e6e518-37d6-4b97-a1d7-af3796e09f15', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontent',
            name='step_content_id',
            field=models.CharField(default='9fe3373e-af79-4d4b-a590-71aee7558026', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='caption_id',
            field=models.CharField(default='7546df64-b977-4d86-9c6c-3581285ca279', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='step_content_detail_id',
            field=models.CharField(default='68c0d15d-2161-407d-bfb3-29a8b88a3d98', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentvoiceover',
            name='step_content_voice_over_id',
            field=models.CharField(default='008a2eed-1e21-4090-aa68-7436d229c875', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrdevice',
            name='device_id',
            field=models.CharField(default='ed2747c8-285b-4614-9c34-7fe3a99b8c8b', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
