# Generated by Django 5.2.8 on 2025-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprocess',
            name='operator_process_id',
            field=models.CharField(default='29d0a7ce-97be-4bbb-9fab-c849e498e4a8', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.CharField(default='57b74a2d-db07-44aa-a1b8-7fef0db5f685', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='session_id',
            field=models.CharField(default='b6b57bbb-107b-4894-a0fd-53b5c5fa390f', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='c82fe6fd-d664-419e-a32d-4e79131b49f8', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session_step_id',
            field=models.CharField(default='7441650e-22b5-4bc9-8fc0-8a1d4c0244cc', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='step_session_id',
            field=models.CharField(default='4d803bc8-f42e-46bb-a597-44d63f0cafe8', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.CharField(default='c839e4d9-5f45-4937-add3-7ff79f267485', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='usage_id',
            field=models.CharField(default='3665ce2e-1bee-4fed-8139-8992d73f1a8c', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.CharField(default='fe505c86-8f78-4cd6-91d4-54344e1c896f', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontent',
            name='step_content_id',
            field=models.CharField(default='6da482de-a4b1-4c23-b036-02d5325f57fd', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='caption_id',
            field=models.CharField(default='619936e5-112b-4d9d-b02b-5dedba093140', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='step_content_detail_id',
            field=models.CharField(default='f9a7b2e9-898f-487e-aa7c-cbf12503aa4d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentvoiceover',
            name='step_content_voice_over_id',
            field=models.CharField(default='d448a7a8-a25c-4500-8477-297ac3156895', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrdevice',
            name='device_id',
            field=models.CharField(default='a0ee8045-a70f-4a8e-9c1a-e9821a6f40c5', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
