# Generated by Django 5.2.8 on 2025-12-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_operatorprocess_operator_process_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operatorprocess',
            name='operator_process_id',
            field=models.CharField(default='2160b20b-0733-4558-9d30-0de1a34dd6df', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.CharField(default='5df0731f-7622-48c1-a9e2-b9b271b7d8da', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='session_id',
            field=models.CharField(default='390cbe01-2b59-45b6-828b-f99f338406ed', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='5c3bdd0a-27f5-4d1c-b44c-75c6798b369d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session_step_id',
            field=models.CharField(default='790a1b80-af6e-4f20-b7e8-329862232fee', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='step_session_id',
            field=models.CharField(default='662be7cd-7aae-4cc5-bad0-f2c5cb3a35f8', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.CharField(default='7014a571-886d-45fd-93f6-49d5284a70aa', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='usage_id',
            field=models.CharField(default='744d0141-8f0a-47cd-92a2-ffa5004a78fc', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.CharField(default='ae182978-3498-41bc-bf31-f48e1d9dff4e', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontent',
            name='step_content_id',
            field=models.CharField(default='70de1a88-4d6c-490d-b5d9-080c9c1cefa1', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='caption_id',
            field=models.CharField(default='a7e9b92a-35b2-4f61-9159-b6289e500685', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='step_content_detail_id',
            field=models.CharField(default='6cafe8e1-22f9-4d2f-9d81-c13ec6ce4c24', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentvoiceover',
            name='step_content_voice_over_id',
            field=models.CharField(default='f0c288a8-9ad0-4c6f-b49e-67af9b8128d8', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrdevice',
            name='device_id',
            field=models.CharField(default='0e82722f-6207-4969-afd7-16def2208f3c', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
