# Generated by Django 5.2.8 on 2025-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_alter_process_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatorprocess',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='operatorsession',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sessionstep',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sessionstepcontentusage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stepcontentcaptions',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stepcontentdetail',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stepcontentvoiceover',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vrdevice',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='operatorprocess',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operatorsession',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sessionstep',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sessionstepcontentusage',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='step',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stepcontentcaptions',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stepcontentdetail',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stepcontentvoiceover',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vrdevice',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operatorprocess',
            name='operator_process_id',
            field=models.CharField(default='db01b3c0-544f-461c-b84b-afc2d91a3d27', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.CharField(default='d3dfbebd-61b9-48f6-ac81-bd4f5394a526', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='session_id',
            field=models.CharField(default='08277098-fa04-46e0-9971-00d3dec49e6a', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='3e469d26-61fc-4ad9-8663-4e89cee97e16', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session_step_id',
            field=models.CharField(default='c5134e97-7fe5-40a9-8877-376ab615e7a7', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='step_session_id',
            field=models.CharField(default='f1a8fc4f-69d1-4d97-8da3-5d3ae52a870e', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.CharField(default='e68e0618-250c-497f-b283-3483d90f79ad', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='usage_id',
            field=models.CharField(default='dc69c5ee-7665-4fdb-9df0-b5d1640f66b8', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.CharField(default='57686f72-c18a-4440-81ef-5c96dc1fa2e3', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontent',
            name='step_content_id',
            field=models.CharField(default='611b7736-bd03-497b-b16a-028b069eca83', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='caption_id',
            field=models.CharField(default='14926ce6-70e2-4d1b-bb74-60113ca337b1', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='step_content_detail_id',
            field=models.CharField(default='fd323244-3690-48dd-92ad-1210d64179ac', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentvoiceover',
            name='step_content_voice_over_id',
            field=models.CharField(default='c854ee99-0dca-405e-8974-9968ae9c72f7', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrdevice',
            name='device_id',
            field=models.CharField(default='22869531-f513-489e-acd1-0d2711840a21', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
