# Generated by Django 5.2.8 on 2025-12-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_operatorprocess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepcontent',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operatorprocess',
            name='operator_process_id',
            field=models.CharField(default='24fbfa5a-508e-4f6a-8c20-b4c356f1e95f', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.CharField(default='4aea6295-44df-4189-993a-f7c7686d4931', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='session_id',
            field=models.CharField(default='00ee381c-40e6-440d-b391-f458ac48f49d', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='336e37ba-1200-4913-8b89-804a76af9cef', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session_step_id',
            field=models.CharField(default='a84cf37a-c246-462e-916e-1435c2686e9b', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='step_session_id',
            field=models.CharField(default='98c72c6a-d2d1-4d9b-9331-43d0f76d47ba', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.CharField(default='0ea9df67-f498-4d49-98a1-9b1d4824f48b', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='usage_id',
            field=models.CharField(default='93323fa4-3c31-49d4-9344-332bb7245c19', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.CharField(default='e0ac9a0b-cc77-4747-af4b-0e1ce84efef4', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontent',
            name='step_content_id',
            field=models.CharField(default='79e3ab89-1b04-41a5-9cb4-e78a12620ba4', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='caption_id',
            field=models.CharField(default='d28c8e54-e05a-443b-a502-f91593c24a37', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='step_content_detail_id',
            field=models.CharField(default='a8ede719-13d3-42a8-a359-744e744e2f50', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentvoiceover',
            name='step_content_voice_over_id',
            field=models.CharField(default='d980607f-cd06-4843-be24-8c7860fa002d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrdevice',
            name='device_id',
            field=models.CharField(default='1dafda2f-56da-459b-b052-81a8f26ec90b', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
