# Generated by Django 5.2.8 on 2025-12-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_alter_operatorprocess_operator_process_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprocess',
            name='operator_process_id',
            field=models.CharField(default='5d8c9a65-deca-40ff-9d6b-c02cf9dc8dca', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.CharField(default='cbb608df-65cc-403f-97d8-ed96125d3c72', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='session_id',
            field=models.CharField(default='b10ce398-4c56-4569-9e7c-6bd2e1d86c70', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='693bee4a-8237-4d8c-86d3-53457b937746', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session_step_id',
            field=models.CharField(default='053277bd-3463-4566-8391-8f0ed7a39dd3', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='step_session_id',
            field=models.CharField(default='3b321417-9ca1-496a-91ab-4126eb48b211', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.CharField(default='95a525f0-8a8d-45f3-983f-3300bb52322a', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='usage_id',
            field=models.CharField(default='c7e81dab-c65b-429b-a6fd-6d809400ffc2', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.CharField(default='c8dc81fc-279d-4f4e-9d52-ad3a997df369', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontent',
            name='step_content_id',
            field=models.CharField(default='ddb23267-cc34-4ea7-8768-be61fe2fc310', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='caption_id',
            field=models.CharField(default='2bd79b9f-9506-41ad-aebb-aa40ccb493ee', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='step_content_detail_id',
            field=models.CharField(default='49498e54-a54e-40a5-8814-7736698cc425', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentvoiceover',
            name='step_content_voice_over_id',
            field=models.CharField(default='8c6bcaa2-7333-4be4-9ee0-ded61df6948f', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrdevice',
            name='device_id',
            field=models.CharField(default='cd6b24ec-ea27-4c62-b4f7-629ec7051e0b', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
