# Generated by Django 5.2.8 on 2025-12-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_alter_operatorprocess_operator_process_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprocess',
            name='operator_process_id',
            field=models.CharField(default='<function uuid4 at 0x000001C30AF63C40>', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.CharField(default='a0ddb6c1-5465-49c1-9329-a714c433bcc3', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatorsession',
            name='session_id',
            field=models.CharField(default='f4fefc6d-6253-4673-ad59-aa89edf68a25', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.CharField(default='9715f7c0-3443-4a13-b1cb-4cd3e7edfcd7', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session_step_id',
            field=models.CharField(default='06311174-bd68-4396-b27a-592d0ffc588b', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='step_session_id',
            field=models.CharField(default='c5171e99-81a4-4fa4-8150-d089b36a6e65', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.CharField(default='913ac33d-105b-4c08-b8cc-394a0fafd535', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='usage_id',
            field=models.CharField(default='8557517a-3274-4fad-b07f-181acb375e84', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_id',
            field=models.CharField(default='fcf0335e-d344-48e2-a535-5326a33a3b68', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontent',
            name='step_content_id',
            field=models.CharField(default='ea3281c4-0421-458e-a00c-effa055d5523', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentcaptions',
            name='caption_id',
            field=models.CharField(default='89d70ae9-d7e2-4743-9901-bbf08ff623a1', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentdetail',
            name='step_content_detail_id',
            field=models.CharField(default='b80351ff-03f9-469e-8f93-0c040b1bf356', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stepcontentvoiceover',
            name='step_content_voice_over_id',
            field=models.CharField(default='042942c1-1883-40c7-bdcc-f40cf5c51fd5', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vrdevice',
            name='device_id',
            field=models.CharField(default='454db838-12da-4021-b45c-7d28e82fd735', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
