# Generated by Django 5.2.8 on 2025-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_alter_operatorsession_operator_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprocess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
