# Generated by Django 5.2.8 on 2025-12-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_operatorprocess_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorsession',
            name='operator_session_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
