# Generated by Django 5.2.8 on 2025-12-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_alter_operatorsession_operator_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionstep',
            name='step_session_id',
        ),
        migrations.AlterField(
            model_name='sessionstep',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='session_steps', to='client.operatorsession', to_field='session_id'),
        ),
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='step_session',
            field=models.ForeignKey(db_column='step_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='content_usages', to='client.sessionstep'),
        ),
    ]
