# Generated by Django 5.2.8 on 2025-12-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_remove_sessionstep_step_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='session_step_content_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
