# Generated by Django 5.2.8 on 2025-12-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_alter_sessionstepcontentusage_session_step_content_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepcontentdetail',
            options={},
        ),
    ]
