# Generated by Django 5.2.8 on 2025-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_alter_stepcontentdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionstepcontentusage',
            name='language',
            field=models.CharField(blank=True, db_column='language_id', max_length=10, null=True),
        ),
    ]
