# Generated by Django 5.2.8 on 2025-12-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_alter_sessionstepcontentusage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionstep',
            name='step',
            field=models.ForeignKey(db_column='step_id', on_delete=django.db.models.deletion.CASCADE, related_name='step_session_steps', to='client.step'),
        ),
    ]
